name: flutter_firebase
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  firebase_core: ^2.8.0
  firebase_ui_auth: ^1.1.17
  google_sign_in: ^6.0.2
  firebase_ui_oauth_google: ^1.0.24
  firebase_messaging: ^14.3.0
  file_picker: ^5.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true